### ISSUE TITLE
Allowfullscreen in iframe

### ISSUE THREAD

**Issue by clara-am** [cgkineo/adapt-iframe#2]
It could be necessary/interesting to include inside the template to 'allowfullscreen'. If you invoke requestFullscreen event from an element, it is returning that it's not allowed. Similar to:

_<iframe src=" " width=" " height=" " frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen scrolling="no"></iframe>_

**Comment by oliverfoster** [comment]
Could you do a pull request?
